### ISSUE TITLE
missing files for icons on the web-interface

### ISSUE THREAD

**Issue by carandraug** [darogan/ParticleStats#10]
The following files are used by the web interface but are not present in the repository or any of the release tarballs:
- Images/heckert_gnu.small.png
- Images/PS_Logo_Simple_100px.png
- Images/compare_logo_100px.png
- Images/directionality_logo_100px.png
- Images/kymograph_logo_100px.png
- Images/PS_Logo_Simple_100px.png

**Comment by darogan** [comment]
All the images are available here: http://www.particlestats.com/Images/

**Comment by carandraug** [comment]
I have added the missing files to the repo (see @2c75d50df5936001520c770b27a16f788f83e52a ). Please consider pulling that since the files hosted somewhere else on the internet, specially without a link to them on the docs, will not be of much help to someone setting this up for their lab.

**Comment by carandraug** [comment]
You have pulled and merged  @2c75d50df5936001520c770b27a16f788f83e52a which I think fixed this. Closing.
