### ISSUE TITLE
remove unused variables and reduce lexical scoping of variables

### ISSUE THREAD

**Issue by carandraug** [darogan/ParticleStats#13]
Not really an issue but while auditing the code and trying to make sense of the web interface, I made a lot of changes which I hope make the code more readable. It also removes a lot of unused variables, warnings about use of undef variables, etc.

Please review the commits on my clone and merge as you see fit. Would be nice if this would be done before the changes to fix issue #11 and #12 which would complicate the merge.

**Comment by darogan** [comment]
Merged
