### ISSUE TITLE
python package is missing ParticleStats_linRegressFit.c

### ISSUE THREAD

**Issue by carandraug** [darogan/ParticleStats#5]
The file ParticleStats_linRegressFit.c refered on setup.py of the python package

```
module1 = Extension('ParticleStats_linRegressFit',
                    sources = ['ParticleStats_linRegressFit.c'])
```

is not present on the tarball.

```
$ md5sum ParticleStats-0.3.tar.gz 
5b22ebec256a812e237d5122127cbde8  ParticleStats-0.3.tar.gz
```

**Comment by darogan** [comment]
Thanks for the issue report. From memory there is a pure python alternative to the c code, but I'll upload the c version tonight.

**Comment by carandraug** [comment]
The c version is on the repository and I have no problems with it. The only issue is that the file is missing from the tarball. Is it missing on purpose or did it just slip by?

**Comment by darogan** [comment]
Its a long time since I made the files. But as there are two versions of the code on using the c code and one not, it may have been deliberate.

I'll check tonight and update the repo. Are you getting the tarball from the particlestats website?
The git version has been updated since then so it should be considered outdated. I'll remove or update the tarball tonight too.

**Comment by carandraug** [comment]
> I'll check tonight and update the repo. Are you getting the tarball from the particlestats website?

Yes. Is there any other place from where to get an installable python package?

**Comment by darogan** [comment]
Not at the moment, but I'll remake the tar.
Would you be interested in a pip version - if so I can take look into
adding ParticleStats there too.

**Comment by carandraug** [comment]
> Not at the moment, but I'll remake the tar. Would you be interested in a pip version - if so I can take look into adding ParticleStats there too.

I am installing it with pip but I don't need it on PyPI. I'll be happy with a tarball that installs.

Actually, I would even prefer being able to make those tarballs myself from development sources.
