### ISSUE TITLE
confusing difference between the two existing web interfaces

### ISSUE THREAD

**Issue by carandraug** [darogan/ParticleStats#9]
At the moment there are two web interfaces to ParticleStats, `ParticleStats_Web.pl` and `ParticleStats_WebStats.pl`.  However, I couldn't find any comment on the purpose of each and they are not mentioned on the pdf manual.

Is any of them deprecated? Or any of them in a work in progress?

**Comment by darogan** [comment]
The ParticleStats_WebStats.pl is not an interface to the main programs, it just reports on the usage stats and last modification date of the scripts. Getting this working isn't critical but the usage stats are useful.

**Comment by carandraug** [comment]
Could you document that somewhere? The difference will still not be obvious to someone setting this up.
